### PR TITLE
Modify the cgiReadFlash function to take offset and length arguments

### PR DESCRIPTION
**Pull request by bjpirt**
This allows a subset of the flash to be downloaded which can be useful for checking that a flash write has been successful without having to download everything.

### CODE REVIEW

**Comment by Spritetm** [comment]
Thanks for the pull req, but I'm gonna let this be for a while... I'm generally messing with the flash functions to enable OTA upgrades at the moment; I am not sure if I can pull your diffs afterwards or if I'm better off manyually integrating the functionality.

**Comment by bjpirt** [comment]
OK - it would be nice to be able to compile the lib with or without support for this because I'm going to be using a custom memory map - I'm also using the rBoot because it's easier to configure where different partitions go (and it's open source so you can actually see what's happening). Getting a little tight on space on a 512k chip now.

**Comment by Spritetm** [comment]
Awesome - I'm messing with multiple ways to create binaries anyway, I'll see if I can find a way to at least make the functionality extendable to rboot.

**Comment by bjpirt** [comment]
Cool - it's a much nicer bootloader IMO. I think Espressif should just switch to it :-)

**Pull request closed without merging**
